name: xpublish
channels:
  - conda-forge
  - defaults
dependencies:
  - xpublish
  - fsspec
  - intake-xarray
  - aiohttp
  - requests
  - pydantic[version='<2']
  - ca-certificates
  - certifi
  - openssl
  - tqdm
  - gribscan
  - asyncio
  - cartopy
  - fsspec
  - holoviews
  - hvplot
  - intake
  - io
  - asyncio
  - nest_asyncio
  - numpy
  - os
  - panel
  - pickle
  - xarray
  - starlette
  - dask
