name: cloudify
channels:
  - conda-forge
dependencies:
  - python==3.11
  - pip
  - git
  - ca-certificates
  - certifi
  - openssl
  - eccodes==2.36.0
  - python-eccodes==1.7.1
  - scipy
#    - git+https://gitlab.dkrz.de/data-infrastructure-services/cloudify.git#egg=cloudify
# does not work because it forces an old eccodes version
