name: cloudify
channels:
  - conda-forge
dependencies:
  - python==3.11
  - pip
  - git
  - ca-certificates
  - certifi
  - openssl
  - eccodes
  - python-eccodes
  - scipy
#    - git+https://gitlab.dkrz.de/data-infrastructure-services/cloudify.git#egg=cloudify
# does not work because it forces an old eccodes version
