name: cloudify
channels:
  - conda-forge
  - defaults
dependencies:
  #- python==3.11
  - pip
  - git
  - ca-certificates
  - certifi
  - openssl
  - eccodes==2.33.0
  - scipy
  - xpublish-opendap
  - pip:
    - xpublish_intake
    - git+https://gitlab.dkrz.de/data-infrastructure-services/cloudify.git#egg=cloudify
