name: cloudify
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.11
  - aiohttp
  - asyncio
  - cartopy
  - dask
  - distributed
  - fsspec
  - gribscan
  - holoviews
  - hvplot
  - intake
  - nest_asyncio
  - numpy
  - panel
  - pydantic<2
  - requests
  - starlette
  - tqdm
  - xarray
  - xpublish
  - pip
  - pydantic[version='<2']
  - ca-certificates
  - certifi
  - openssl
  - pip:
    - git+https://gitlab.dkrz.de/data-infrastructure-services/xpublish.git#egg=cloudify
